---
- include_vars: app.yml

- name: 'user {{ node_app.user }}'
  user:
    name: '{{ node_app.user }}'
    shell: /bin/sh
    home: '/home/{{ node_app.user }}'
    createhome: yes

- name: 'dir {{ node_app.path }}'
  file:
    path: '{{ node_app.path }}'
    state: directory

- name: 'git {{ node_app.gitsrc }}'
  git:
    repo: '{{ node_app.gitsrc }}'
    dest: '{{ node_app.path }}'
    update: '{{ node_app.gitupdate }}'
    force: '{{ node_app.gitforce }}'
  when: '"gitsrc" in node_app'
  register: gitted

- name: 'chown -R {{ node_app.user }} {{ node_app.path }}'
  file:
    path: '{{ node_app.path }}'
    mode: 'u=rwX,g=rwX,o=rX'
    owner: '{{ node_app.user }}'
    recurse: yes

- name: 'search package.json'
  stat:
    path: '{{ node_app.path }}/package.json'
  register: node_has_package_json

- name: config files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest | regex_replace("^([^/])",node_app.path+"/\1") }}'
  with_items: '{{ node_app.confs | default([]) }}'
  register: confs

- name: npm install
  command: 'npm install'
  args:
    chdir: '{{ node_app.path }}'
  become: '{{ node_app.user }}'
  when: node_has_package_json.stat.exists and gitted.changed

- name: install service
  template:
    src: FreeBSD-rc.j2
    dest: '/usr/local/etc/rc.d/{{ node_app.name }}'
    mode: '0755'

- name: restart app
  block:
    - name: stop app
      service:
        name: '{{ node_app.name }}'
        state: stopped
      failed_when: False
    - name: start app
      service:
        name: '{{ node_app.name }}'
        state: started
  when: gitted.changed or confs.changed
