---
- include_vars: app.yml

- user:
    name: '{{ node_app.user }}'
    shell: /bin/sh
    home: '/home/{{ node_app.user }}'
    createhome: yes

- file:
    path: '{{ node_app.path }}'
    state: directory

- name: git
  git:
    repo: '{{ node_app.gitsrc }}'
    dest: '{{ node_app.path }}'
    update: '{{ node_app.update | default(True) | bool }}'
    force: '{{ node_app.update | default(True) | bool }}'
  when: '"gitsrc" in node_app'
  register: gitted

- file:
    path: '{{ node_app.path }}'
    mode: 'u=rwX,g=rwX,o=rX'
    owner: '{{ node_app.user }}'
    recurse: yes

- stat:
    path: '{{ node_app.path }}/package.json'
  register: node_has_package_json

- name: config files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest | regex_replace("^([^/])",node_app.path+"/\1") }}'
  with_items: '{{ node_app.confs | default([]) }}'
  register: confs

- name: npm install
  command: 'npm install'
  args:
    chdir: '{{ node_app.path }}'
  become: '{{ node_app.user }}'
  when: node_has_package_json.stat.exists and gitted.changed

- name: install service
  template:
    src: FreeBSD-rc.j2
    dest: '/usr/local/etc/rc.d/{{ node_app.name }}'
    mode: '0755'

- name: enable+start service
  service:
    name: '{{ node_app.name }}'
    enables: yes
    state: started
  register: startapp

- name: restart app if needed
  block:
    - name: stop app
      service:
        name: '{{ node_app.name }}'
        state: stopped
      failed_when: False
    - name: start app
      service:
        name: '{{ node_app.name }}'
        state: started
  when: ( gitted.changed or confs.changed ) and not startapp.changed
