---
# tasks file for criecm.node
- name: 'include os'
  include_vars: '{{ item }}'
  with_first_found:
    - skip: True
    - '{{ ansible_os_family }}.yml'

# install node
- name: 'install for {{ ansible_os_family }}'
  include_tasks: '{{ ansible_os_family }}-install.yml'

# install app(s)
- name: 'app {{ oneapp.name }}'
  include_tasks: app.yml
  with_items: '{{ node_apps }}'
  loop_control:
    loop_var: oneapp


