---
# app default vars
default_node_app:
  name: '{{ oneapp.name | mandatory }}'
  user: '{{ oneapp.name | mandatory }}'
  path: '/home/{{ oneapp.name }}/{{ oneapp.name }}'
  update: '{{ node_update_git }}'
  force: '{{ node_force_git }}'
  syslog_tag: '{{ oneapp.name }}'
  use_syslog: False
  script: app.js
  env: developement

node_app: '{{ default_node_app | combine(oneapp) }}'
